

services:
  webserver:
    build:
      context: .
    ports:
      - 8000:8000
    command: gunicorn bookersite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/app/static
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
  
  nginx:
    build: ./nginx
    volumes: 
      - static:/static
    ports:
      - 80:80
    depends_on:
      - webserver

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
  static:


