# Generated by Django 5.0.7 on 2024-08-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker_engine', '0002_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
